# permissions for end users to edit stores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: store-editor-role
rules:
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - stores/status
  verbs:
  - get
