# permissions for end users to edit timers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timer-editor-role
rules:
- apiGroups:
  - vanus.linkall.com
  resources:
  - timers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vanus.linkall.com
  resources:
  - timers/status
  verbs:
  - get
